  export let data = [
   //{id:0, brand:"", name:"", category:[""], subcategory:[""], amount:1, price:2.5, description:"", nutriScore:"", previewImg:""},
        ////////////////////////////////////////////////////////////////ZUIVEL////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////EIREN////////////////////////////////////////////////////////////////
        {id:1, brand:"BONI", name:"Eiren wit", category:["Zuivel"], subcategory:["Eiren"], amount:1, price:2.49, description:"Het plantaardige voer met lijnzaadolie zorgt voor alfa-linoleenzuur (ALA), wat bijdraagt tot de instandhouding van normale cholesterolgehalten in het bloed*. * = bij dagelijkse inname van 2 g ALA.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/80/89/asset-1928089.jpg"},
        {id:2, brand:"BONI BIO", name:"Ei vrije uitloop M", category:["Zuivel"], subcategory:["Eiren"], amount:1, price:3.90, description:"Het plantaardige voer met lijnzaadolie zorgt voor alfa-linoleenzuur (ALA), wat bijdraagt tot de instandhouding van normale cholesterolgehalten in het bloed*. * = bij dagelijkse inname van 2 g ALA.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/06/31/asset-2660631.jpg"},
        {id:3, brand:"OVYTA", name:"Eiwit", category:["Zuivel"], subcategory:["Eiren"], amount:1, price:2.19, description:"Het plantaardige voer met lijnzaadolie zorgt voor alfa-linoleenzuur (ALA), wat bijdraagt tot de instandhouding van normale cholesterolgehalten in het bloed*. * = bij dagelijkse inname van 2 g ALA.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/28/39/asset-2032839.jpg"},
        {id:4, brand:"BONI", name:"Belgisch scharrelei M", category:["Zuivel"], subcategory:["Eiren"], amount:1, price:6.19, description:"Het plantaardige voer met lijnzaadolie zorgt voor alfa-linoleenzuur (ALA), wat bijdraagt tot de instandhouding van normale cholesterolgehalten in het bloed*. * = bij dagelijkse inname van 2 g ALA.", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/26/49/asset-1262649.jpg"},
        ////////////////////////////////////////////////////////////////Melk////////////////////////////////////////////////////////////////
        {id:5, brand:"CAMPINA", name:"Halfvolle melk lactosevrij", category:["Zuivel"], subcategory:["Melk"], amount:1, price:1.95, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/nl_be/05/16/asset-2520516.jpg"},
        {id:6, brand:"EVERYDAY", name:"Volle melk brik", category:["Zuivel"], subcategory:["Melk"], amount:1, price:0.70, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/19/91/asset-1391991.jpg"},
        {id:7, brand:"JOYVALLE", name:"Volle AA melk brik", category:["Zuivel"], subcategory:["Melk"], amount:1, price:1.41, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/nl_be/05/00/asset-2520500.jpg"},
        {id:8, brand:"FAIREBEL", name:"Volle melk brik", category:["Zuivel"], subcategory:["Melk"], amount:1, price:1.23, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/51/90/asset-2635190.jpg"},
        {id:9, brand:"BONI", name:"Halfvolle melk brik", category:["Zuivel"], subcategory:["Melk"], amount:1, price:1.84, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/87/89/asset-2758789.jpg"},
        ////////////////////////////////////////////////////////////////KAAS////////////////////////////////////////////////////////////////
        {id:10, brand:"PASSENDALE", name:"Jonge kaas sneden", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:5.64, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/45/61/asset-2314561.jpg"},
        {id:11, brand:"BRUGGE", name:"Kaas oud sneetjes", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:8.30, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/46/45/asset-2694645.jpg"},
        {id:12, brand:"LEERDAMMER", name:"Kaas Lightlife sneetjes", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:4.43, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/06/36/asset-2340636.jpg"},
        {id:13, brand:"CHAUMES", name:"Kaas zacht 9 sneetjes", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:4.65, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/31/09/asset-743109.jpg"},
        {id:14, brand:"CHAVROUX", name:"Geitenkaas sneetjes", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:4.19, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/35/05/asset-1643505.jpg"},
        ////////////////////////////////////////////////////////////////VlEES////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////Charcuterie////////////////////////////////////////////////////////////////
        {id:15, brand:"MARCASSOU", name:"Saucisson de Table sn.", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:3.79, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/86/25/asset-2148625.jpg"},
        {id:16, brand:"BONI", name:"Chorizo zacht sneden", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:1.39, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/93/94/asset-2509394.jpg"},
        {id:17, brand:"EVERYDAY", name:"Salami z.look sneetjes", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:1.33, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/42/37/asset-624237.jpg"},
        {id:18, brand:"ECONOM", name:"Salami blokjes", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:9.79, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/08/36/asset-2120836.jpg"},
        {id:19, brand:"BONI", name:"Salami Milano GV", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:3.31, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/57/96/asset-1525796.jpg"},

        {id:20, brand:"HERTA", name:"Superieur ham natuur 3 sn.", category:["Vlees"], subcategory:["Charcuterie", "Ham"], amount:1, price:2.25, description:"Gekookte hesp/ham op ambachtelijke wijze gemaakt volgens het recept van Kai Meyers. Voor mij 'ene me hesp' alsjeblieft!", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/53/93/asset-2095393.jpg"},
        {id:21, brand:"AH", name:"Mosterdspek", category:["Vlees"], subcategory:["Charcuterie", "Ham"], amount:1, price:2.16, description:"Gekookte hesp/ham op ambachtelijke wijze gemaakt volgens het recept van Kai Meyers. Voor mij 'ene me hesp' alsjeblieft!", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/80/03/asset-2708003.jpg"},
        {id:22, brand:"BONI BIO", name:"Gekookte ham", category:["Vlees"], subcategory:["Charcuterie", "Ham"], amount:1, price:4.55, description:"Gekookte hesp/ham op ambachtelijke wijze gemaakt volgens het recept van Kai Meyers. Voor mij 'ene me hesp' alsjeblieft!", nutriScore:"c", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/08/55/asset-2130855.jpg"},
        {id:23, brand:"EVERYDAY", name:"Ham ovengebakken", category:["Vlees"], subcategory:["Charcuterie", "Ham"], amount:1, price:3.98, description:"Gekookte hesp/ham op ambachtelijke wijze gemaakt volgens het recept van Kai Meyers. Voor mij 'ene me hesp' alsjeblieft!", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/24/54/asset-912454.jpg"},

        {id:24, brand:"AH", name:"Beenhamsalade", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:1.85, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/30/13/asset-2503013.jpg"},
        {id:25, brand:"DÉLIO", name:"Salade kip curry", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:3.39, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/37/89/asset-1523789.jpg"},
        {id:26, brand:"BONI", name:"Gv vleessalade", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:1.84, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/82/74/asset-2428274.jpg"},
        {id:27, brand:"EVERYDAY", name:"Tonijnsalade", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:1.09, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/83/10/asset-2428310.jpg"},
        {id:28, brand:"BONI", name:"Orientaalse salade", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:1.80, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/74/29/asset-2617429.jpg"},

        {id:29, brand:"AOSTE", name:"Crèmepaté", category:["Vlees"], subcategory:["Charcuterie", "Paté"], amount:1, price:2.13, description:"Een smeuïge crèmepaté die werd afgewerkt met stukjes appel om bij elke hap een lichtzoete toets vrij te geven. Ideaal voor op de boterham, maar zeker ook een aanrader voor op toastjes bij een aperitiefje.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/04/76/asset-850476.jpg"},
        {id:30, brand:"BONI", name:"Boerenpaté", category:["Vlees"], subcategory:["Charcuterie", "Paté"], amount:1, price:2.06, description:"Een smeuïge crèmepaté die werd afgewerkt met stukjes appel om bij elke hap een lichtzoete toets vrij te geven. Ideaal voor op de boterham, maar zeker ook een aanrader voor op toastjes bij een aperitiefje.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/42/39/asset-594239.jpg"},
        {id:31, brand:"EVERYDAY", name:"Crèmepaté vlootje", category:["Vlees"], subcategory:["Charcuterie", "Paté"], amount:1, price:0.89, description:"Een smeuïge crèmepaté die werd afgewerkt met stukjes appel om bij elke hap een lichtzoete toets vrij te geven. Ideaal voor op de boterham, maar zeker ook een aanrader voor op toastjes bij een aperitiefje.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/37/06/asset-2053706.jpg"},

        {id:32, brand:"HERTA", name:"Kip aan spit -25% zout", category:["Vlees"], subcategory:["Charcuterie", "Kip & kalkoen"], amount:1, price:2.99, description:"Kippenwit is te danken aan het exclusieve gebruik van de magerste en zuiverste kipfilets (100% filet). De filets worden op dezelfde wijze bereid als gekookte ham. Daarna geeft het ambachtelijke bakproces in de oven de filets een lekkere grillsmaak evenals het mooie, goudbruine korstje.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/66/41/asset-2446641.jpg"},
        {id:33, brand:"AOSTE", name:"Disney kipworstj familypack", category:["Vlees"], subcategory:["Charcuterie", "Kip & kalkoen"], amount:1, price:4.49, description:"Kippenwit is te danken aan het exclusieve gebruik van de magerste en zuiverste kipfilets (100% filet). De filets worden op dezelfde wijze bereid als gekookte ham. Daarna geeft het ambachtelijke bakproces in de oven de filets een lekkere grillsmaak evenals het mooie, goudbruine korstje.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/00/37/asset-2790037.jpg"},
        {id:34, brand:"AOSTE PLUS", name:"Kip.stukj.gegrild natuur", category:["Vlees"], subcategory:["Charcuterie", "Kip & kalkoen"], amount:1, price:2.49, description:"Kippenwit is te danken aan het exclusieve gebruik van de magerste en zuiverste kipfilets (100% filet). De filets worden op dezelfde wijze bereid als gekookte ham. Daarna geeft het ambachtelijke bakproces in de oven de filets een lekkere grillsmaak evenals het mooie, goudbruine korstje.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/83/43/asset-2788343.jpg"},
        {id:35, brand:"BONI", name:"Mini gevogelte balletjes", category:["Vlees"], subcategory:["Charcuterie", "Kip & kalkoen"], amount:1, price:3.99, description:"Kippenwit is te danken aan het exclusieve gebruik van de magerste en zuiverste kipfilets (100% filet). De filets worden op dezelfde wijze bereid als gekookte ham. Daarna geeft het ambachtelijke bakproces in de oven de filets een lekkere grillsmaak evenals het mooie, goudbruine korstje.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/22/76/asset-2132276.jpg"},
        ////////////////////////////////////////////////////////////////GROENTEN////////////////////////////////////////////////////////////////
        {id:36, brand:"FLORETTE", name:"Kropsla fijne kruiden", category:["Groenten"], subcategory:["Sla"], amount:1, price:2.89, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/93/99/asset-2439399.jpg"},
        {id:37, brand:"BONI BIO", name:"Jonge sla", category:["Groenten"], subcategory:["Sla"], amount:1, price:1.99, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/90/32/asset-2419032.jpg"},
        {id:38, brand:"FLANDRIA", name:"Sla multicolor", category:["Groenten"], subcategory:["Sla"], amount:1, price:1.15, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/28/14/asset-392814.jpg"},
        {id:39, brand:"AH", name:"Ijsbergsla", category:["Groenten"], subcategory:["Sla"], amount:1, price:0.99, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/46/74/asset-1224674.jpg"},
        {id:40, brand:"BONI", name:"Rauwkostmix", category:["Groenten"], subcategory:["Wortel","Witte kool"], amount:1, price:1.19, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/55/46/asset-2475546.jpg"},
        {id:41, brand:"BONI", name:"Geraspte wortelen", category:["Groenten"], subcategory:["Wortel"], amount:1, price:0.55, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/55/45/asset-2475545.jpg"},
        {id:42, brand:"BONI", name:"Witte kool geraspt", category:["Groenten"], subcategory:["Witte kool"], amount:1, price:1.19, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/58/50/asset-2675850.jpg"},
        {id:43, brand:"SALANOVA", name:"Sla mix", category:["Groenten"], subcategory:["Sla"], amount:1, price:0.99, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/62/91/asset-2136291.jpg"},
        {id:44, brand:"BONI", name:"Mix kiemen", category:["Groenten"], subcategory:["Kiemen"], amount:1, price:1.89, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/18/58/asset-2451858.jpg"},
        {id:45, brand:"AH", name:"Andijvie", category:["Groenten"], subcategory:["Andijvie"], amount:1, price:1.89, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/20/95/asset-362095.jpg"},
        {id:46, brand:"TOMA'", name:"Box tomaten", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:4.99, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/42/07/asset-1744207.jpg"},
        {id:47, brand:"AH", name:"Tomaten extra", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:2.39, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/71/29/asset-1147129.jpg"},
        {id:46, brand:"BONI", name:"Kerstomaatjes tros", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:2.99, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/00/29/asset-2330029.jpg"},
        {id:49, brand:"AGROMONTE", name:"Pass.salsa kerstom. glas", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:2.89, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/45/46/asset-2274546.jpg"},
        {id:50, brand:"ELVEA", name:"Tomaten blokjes gepeld", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:1.99, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/89/30/asset-1718930.jpg"},
        {id:51, brand:"BONI", name:"Taboulé paprika-tomaat", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:2.29, description:"Omdat we willen dat jij optimaal kan genieten van onze verse producten, verkopen we steeds meer groenten en fruit per stuk. Zo kan je zelf kiezen welke én hoeveel exemplaren je in je winkelkar legt. ", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/76/14/asset-2797614.jpg"},
        ////////////////////////////////////////////////////////////////Huishoudproducten////////////////////////////////////////////////////////////////
        {id:52, brand:"Clorox", name:"Clorox Disinfecting Bleach", category:["Huishouden"], subcategory:["Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten"], amount:1, price:41.00, description:"", nutriScore:"n/a", previewImg:"https://i5.walmartimages.com/asr/bcd49e3f-aab2-44e5-82e0-1bcb1ca4b664_1.572cbe96f87082945f06931d8b31c205.jpeg"},
        {id:53, brand:"DASH", name:"Wasdraadfris", category:["Huishouden"], subcategory:[""], amount:1, price:13.94, description:"Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten", nutriScore:"n/a", previewImg:"https://static.colruytgroup.com/images/500x500/std.lang.all/59/51/asset-2145951.jpg"},
        {id:54, brand:"DASH", name:"Wasdraadfris bloemen", category:["Huishouden"], subcategory:[""], amount:1, price:13.94, description:"Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/21/06/asset-2782106.jpg"},
        {id:56, brand:"AH", name:"Mop + emmer", category:["Huishouden"], subcategory:[""], amount:1, price:13.94, description:"Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten", nutriScore:"n/a", previewImg:"https://media.discordapp.net/attachments/251688346672168963/978583690550595644/MicrosoftTeams-image.png?width=450&height=676"},
        {id:57, brand:"VILEDA", name:"Dweilen Colors", category:["Huishouden"], subcategory:[""], amount:1, price:4.15, description:"Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/39/36/asset-2123936.jpg"},
        {id:58, brand:"CURVER", name:"Emmer 13 L", category:["Huishouden"], subcategory:[""], amount:1, price:5.99, description:"Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/62/00/asset-336200.jpg"},
        {id:59, brand:"AH", name:"Latex handschoenen", category:["Huishouden"], subcategory:[""], amount:1, price:17.45, description:"Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten", nutriScore:"n/a", previewImg:"https://media.discordapp.net/attachments/251688346672168963/978583828559970334/MicrosoftTeams-image_2.png"},
        {id:60, brand:"BONI SELECTION", name:"Vloerwisser met steel", category:["Huishouden"], subcategory:[""], amount:1, price:17.45, description:"Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/nl_be/91/59/asset-2299159.jpg"},
        {id:61, brand:"AH", name:"Vuilniszakken zwart", category:["Huishouden"], subcategory:[""], amount:1, price:17.45, description:"Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/nl_be/91/59/asset-2299159.jpg"},
        {id:62, brand:"TESSA", name:"Duct Tape", category:["Huishouden"], subcategory:[""], amount:1, price:11.16, description:"Maak het huishouden gemakkelijk en leuk met ons assortiment unieke producten! Zo kun je in onze recycle prullenbakken al jouw afval scheiden, maak je jouw huis weer brandschoon met onze schoonmaakapparaten", nutriScore:"n/a", previewImg:"https://media.discordapp.net/attachments/251688346672168963/978583828220243998/MicrosoftTeams-image_3.png?width=547&height=675"},
        ////////////////////////////////////////////////////////////////Keukengerei////////////////////////////////////////////////////////////////
        {id:63, brand:"Zwilling", name:"Chef mes", category:["Keukengerei"], subcategory:[""], amount:1, price:10.12, description:"Ben je op zoek naar een ruime keuze in keukenapparaten en -gerei, zoals messen en pannen of speciale keuken opbergers en koffiezetapparaten? Zoek dan niet verder, ons assortiment heeft voor ieder wat wils.", nutriScore:"n/a", previewImg:"https://media.discordapp.net/attachments/251688346672168963/978583827570110494/MicrosoftTeams-image_5.png?width=1014&height=676"},
        {id:64, brand:"KitchenMonster", name:"Koksmes Damascus", category:["Keukengerei"], subcategory:[""], amount:1, price:69.00, description:"Ben je op zoek naar een ruime keuze in keukenapparaten en -gerei, zoals messen en pannen of speciale keuken opbergers en koffiezetapparaten? Zoek dan niet verder, ons assortiment heeft voor ieder wat wils.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/JW62MpqD4Y2D/28WjyVv/1194x1200.jpg"},
        {id:65, brand:"Brabantia", name:"Pureestamper", category:["Keukengerei"], subcategory:[""], amount:1, price:7.01, description:"Ben je op zoek naar een ruime keuze in keukenapparaten en -gerei, zoals messen en pannen of speciale keuken opbergers en koffiezetapparaten? Zoek dan niet verder, ons assortiment heeft voor ieder wat wils.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/qwOzzW5A7k3/489x1200.jpg"},
        {id:66, brand:"OXO", name:"Dunschiller", category:["Keukengerei"], subcategory:[""], amount:1, price:8.95, description:"Ben je op zoek naar een ruime keuze in keukenapparaten en -gerei, zoals messen en pannen of speciale keuken opbergers en koffiezetapparaten? Zoek dan niet verder, ons assortiment heeft voor ieder wat wils.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/7vom6ZVV9nQ/643x1200.jpg"},
        {id:67, brand:"Westmark", name:"Groenteschiller", category:["Keukengerei"], subcategory:[""], amount:1, price:12.99, description:"Ben je op zoek naar een ruime keuze in keukenapparaten en -gerei, zoals messen en pannen of speciale keuken opbergers en koffiezetapparaten? Zoek dan niet verder, ons assortiment heeft voor ieder wat wils.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/wE7RzX73ZYkm/DR0ZkkA/1200x1050.jpg"},
        {id:68, brand:"AH", name:"Bamboe snijplank", category:["Keukengerei"], subcategory:[""], amount:1, price:17.99, description:"Ben je op zoek naar een ruime keuze in keukenapparaten en -gerei, zoals messen en pannen of speciale keuken opbergers en koffiezetapparaten? Zoek dan niet verder, ons assortiment heeft voor ieder wat wils.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/BBBRgPO31onW/6XW6kWL/1200x584.jpg"},
        {id:69, brand:"Tefal", name:"Braadpan", category:["Keukengerei"], subcategory:[""], amount:1, price:37.00, description:"Ben je op zoek naar een ruime keuze in keukenapparaten en -gerei, zoals messen en pannen of speciale keuken opbergers en koffiezetapparaten? Zoek dan niet verder, ons assortiment heeft voor ieder wat wils.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/nNr26J7x4EEP/59YrQoX/550x257.jpg"},
        {id:70, brand:"ISENVI", name:"Pannenset 6 delig", category:["Keukengerei"], subcategory:[""], amount:1, price:129.99, description:"Ben je op zoek naar een ruime keuze in keukenapparaten en -gerei, zoals messen en pannen of speciale keuken opbergers en koffiezetapparaten? Zoek dan niet verder, ons assortiment heeft voor ieder wat wils.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/5L1pgV2RkB2K/550x488.jpg"},
        ////////////////////////////////////////////////////////////////Tuingerief////////////////////////////////////////////////////////////////
        {id:71, brand:"GARDENA", name:"Snoeischaar", category:["Tuingerief"], subcategory:[""], amount:1, price:10.12, description:"Er zit 25 jaar garantie op dit product van GARDENA", nutriScore:"n/a", previewImg:"https://media.s-bol.com/N87N7q6ypx7N/1200x460.jpg"},
        {id:72, brand:"Kärcher", name:"FJ 6 Foam Jet", category:["Tuingerief"], subcategory:[""], amount:1, price:16.12, description:"Voor de reiniging van auto's, motoren en voor het aanbrengen van reinigingsmiddelen op stenen en houten oppervlakken en gevels", nutriScore:"n/a", previewImg:"https://media.s-bol.com/OZBgDMZKjgGg/pQ0QpvX/867x1200.jpg"},
        {id:73, brand:"Gardebruk", name:"Tuin afvalzak", category:["Tuingerief"], subcategory:[""], amount:1, price:17.12, description:"Deze tuin afvalzak heeft 3 stevige handgrepen. Twee handgrepen voor het Transport en een handvat voor het Legen.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/N7oKpQ3WoJmD/X6JGkno/550x571.jpg"},
        {id:74, brand:"Powerplus", name:"POWXGSG2 Tuinafvalzak", category:["Tuingerief"], subcategory:[""], amount:1, price:10.12, description:"Deze tuin afvalzak heeft 3 stevige handgrepen. Twee handgrepen voor het Transport en een handvat voor het Legen.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/gMpXnlWxMjOj/vQjAO65/1091x1200.jpg"},
        {id:75, brand:"vidaXL", name:"Boot touw", category:["Tuingerief"], subcategory:[""], amount:1, price:10.12, description:"Deze vidaXL is een stevig touw. Te gebruiken als boottouw, koord, bindtouw, scheepstouw, vismagneet touw, schommeltouw.", nutriScore:"n/a", previewImg:"https://media.discordapp.net/attachments/251688346672168963/978583830275432458/MicrosoftTeams-image_6.png?width=676&height=676"},
        {id:76, brand:"AH", name:"Draadtester", category:["Tuingerief"], subcategory:[""], amount:1, price:10.12, description:"Met deze draadtester kunt u eenvoudig een draadbreuk opsporen. Nadat u de zender tegen de draad heeft geplaatst, kunt u met de ontvanger de breuk opzoeken.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/qVPwBypkPDvr/zmzOj1y/1200x1162.jpg"},
        {id:78, brand:"EISTER", name:"Gel connector", category:["Tuingerief"], subcategory:[""], amount:1, price:10.12, description:"Deze draadconnector wordt gebruikt om een beschadigde perimeter draad of begrenzingsdraad tbv robotmaaiers terug aan elkaar te zetten of een bijkomende zone af te splitsen of af te bakenen.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/m21XYjVLK45p/zmyx8Wq/987x1200.jpg"},
        {id:79, brand:"Talen Tools", name:"Onkruidborstel", category:["Tuingerief"], subcategory:[""], amount:1, price:10.12, description:"Deze onkruidborstel is geschikt voor het verwijderen van het grove en fijne onkruid. Het fijne onkruid kunt u verwijderen met de borstel en het grove onkruid kan verwijdert worden met het krabhakje.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/JPgQmn8vYmR2/692x1200.jpg"},
        {id:80, brand:"WOLF-Garten", name:"voegenkrabber", category:["Tuingerief"], subcategory:[""], amount:1, price:10.12, description:"De Wolf-Garten KF-2K Voegenkrabber is ideaal voor het verwijderen van gras, mos en onkruid tussen bijvoorbeeld tegels, langs muren, trappen etc. Deze Krabber heeft een comfort grip op het handvat en ondersteunt de trekbeweging.", nutriScore:"n/a", previewImg:"https://media.s-bol.com/YMAgA6G0wR7n/1200x1073.jpg"},
        ////////////////////////////////////////////////////////////////VIS////////////////////////////////////////////////////////////////
        {id:81, brand:"BONI", name:"Zeewolf haasje MSC", category:["Vis"], subcategory:[""], amount:1, price:10.12, description:"Deze smakelijke verse vis is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/37/68/asset-2393768.jpg"},
        {id:82, brand:"BONI BIO", name:"Zalmfilet met huid", category:["Vis"], subcategory:[""], amount:1, price:10.12, description:"Deze smakelijke verse vis is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/75/29/asset-2527529.jpg"},
        {id:83, brand:"BONI", name:"Ansjovisfilet olie nat. MSC", category:["Vis"], subcategory:[""], amount:1, price:10.12, description:"Deze smakelijke verse vis is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/01/63/asset-2730163.jpg"},
        {id:84, brand:"BONI", name:"Zalmburger graatloos", category:["Vis"], subcategory:[""], amount:1, price:10.12, description:"Deze smakelijke verse vis is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/83/28/asset-2788328.jpg"},
        {id:85, brand:"EVERYDAY", name:"Noorse gerookte zalm sn.", category:["Vis"], subcategory:[""], amount:1, price:10.12, description:"Deze smakelijke verse vis is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/93/30/asset-2509330.jpg"},
        {id:86, brand:"BONI", name:"Gekookte zalm Bellevue", category:["Vis"], subcategory:[""], amount:1, price:10.12, description:"Deze smakelijke verse vis is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.", nutriScore:"c", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/98/62/asset-2509862.jpg"},
        {id:87, brand:"BONI", name:"Gerookte makreelfilet", category:["Vis"], subcategory:[""], amount:1, price:10.12, description:"Deze smakelijke verse vis is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/69/66/asset-566966.jpg"},
        {id:88, brand:"AH", name:"Zeeuwse mossel op azijn MSC", category:["Vis"], subcategory:[""], amount:1, price:10.12, description:"Deze smakelijke verse vis is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/96/58/asset-959658.jpg"},
        {id:89, brand:"EVERYDAY", name:"Surimisticks", category:["Vis"], subcategory:[""], amount:1, price:10.12, description:"Deze smakelijke verse vis is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.", nutriScore:"c", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/38/32/asset-1703832.jpg"},
  ];



//export default{
//  dataObject
//}