  export let data = [
   //{id:0, brand:"", name:"", category:[""], subcategory:[""], amount:1, price:2.5, description:"", nutriScore:"", previewImg:""},
        ////////////////////////////////////////////////////////////////ZUIVEL////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////EIREN////////////////////////////////////////////////////////////////
        {id:1, brand:"BONI", name:"Eiren wit", category:["Zuivel"], subcategory:["Eiren"], amount:1, price:2.49, description:"Het plantaardige voer met lijnzaadolie zorgt voor alfa-linoleenzuur (ALA), wat bijdraagt tot de instandhouding van normale cholesterolgehalten in het bloed*. * = bij dagelijkse inname van 2 g ALA.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/80/89/asset-1928089.jpg"},
        {id:2, brand:"BONI BIO", name:"Ei vrije uitloop M", category:["Zuivel"], subcategory:["Eiren"], amount:1, price:3.90, description:"Het plantaardige voer met lijnzaadolie zorgt voor alfa-linoleenzuur (ALA), wat bijdraagt tot de instandhouding van normale cholesterolgehalten in het bloed*. * = bij dagelijkse inname van 2 g ALA.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/06/31/asset-2660631.jpg"},
        {id:3, brand:"OVYTA", name:"Eiwit", category:["Zuivel"], subcategory:["Eiren"], amount:1, price:2.19, description:"Het plantaardige voer met lijnzaadolie zorgt voor alfa-linoleenzuur (ALA), wat bijdraagt tot de instandhouding van normale cholesterolgehalten in het bloed*. * = bij dagelijkse inname van 2 g ALA.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/28/39/asset-2032839.jpg"},
        {id:4, brand:"BONI", name:"Belgisch scharrelei M", category:["Zuivel"], subcategory:["Eiren"], amount:1, price:6.19, description:"Het plantaardige voer met lijnzaadolie zorgt voor alfa-linoleenzuur (ALA), wat bijdraagt tot de instandhouding van normale cholesterolgehalten in het bloed*. * = bij dagelijkse inname van 2 g ALA.", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/26/49/asset-1262649.jpg"},
        ////////////////////////////////////////////////////////////////Melk////////////////////////////////////////////////////////////////
        {id:5, brand:"CAMPINA", name:"Halfvolle melk lactosevrij", category:["Zuivel"], subcategory:["Melk"], amount:1, price:1.95, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/nl_be/05/16/asset-2520516.jpg"},
        {id:6, brand:"EVERYDAY", name:"Volle melk brik", category:["Zuivel"], subcategory:["Melk"], amount:1, price:0.70, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/19/91/asset-1391991.jpg"},
        {id:7, brand:"JOYVALLE", name:"Volle AA melk brik", category:["Zuivel"], subcategory:["Melk"], amount:1, price:1.41, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/nl_be/05/00/asset-2520500.jpg"},
        {id:8, brand:"FAIREBEL", name:"Volle melk brik", category:["Zuivel"], subcategory:["Melk"], amount:1, price:1.23, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/51/90/asset-2635190.jpg"},
        {id:9, brand:"BONI", name:"Halfvolle melk brik", category:["Zuivel"], subcategory:["Melk"], amount:1, price:1.84, description:"heerlijke melk van bij ons, opgehaald bij Belgische boeren die zorg dragen voor dier en natuur. De koeien die de melk leveren, staan minimaal 120 dagen per jaar buiten in de weide, en dit minstens 6 uur per dag. Deze koeien krijgen bovendien een natuurlijke en evenwichtige voeding.", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/87/89/asset-2758789.jpg"},
        ////////////////////////////////////////////////////////////////KAAS////////////////////////////////////////////////////////////////
        {id:10, brand:"PASSENDALE", name:"Jonge kaas sneden", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:5.64, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/45/61/asset-2314561.jpg"},
        {id:11, brand:"BRUGGE", name:"Kaas oud sneetjes", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:8.30, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/46/45/asset-2694645.jpg"},
        {id:12, brand:"LEERDAMMER", name:"Kaas Lightlife sneetjes", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:4.43, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/06/36/asset-2340636.jpg"},
        {id:13, brand:"CHAUMES", name:"Kaas zacht 9 sneetjes", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:4.65, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/31/09/asset-743109.jpg"},
        {id:14, brand:"CHAVROUX", name:"Geitenkaas sneetjes", category:["Zuivel"], subcategory:["Kaas"], amount:1, price:4.19, description:"Halfharde, authentieke kaas in de vorm van een boerenbrood, natuurlijk gerijpt met eetbare korst. Licht verteerbaar door zijn luchtige gaatjesstructuur.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/35/05/asset-1643505.jpg"},
        ////////////////////////////////////////////////////////////////VlEES////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////Charcuterie////////////////////////////////////////////////////////////////
        {id:15, brand:"MARCASSOU", name:"Saucisson de Table sn.", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:3.79, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/86/25/asset-2148625.jpg"},
        {id:16, brand:"BONI", name:"Chorizo zacht sneden", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:1.39, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/93/94/asset-2509394.jpg"},
        {id:17, brand:"EVERYDAY", name:"Salami z.look sneetjes", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:1.33, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/42/37/asset-624237.jpg"},
        {id:18, brand:"ECONOM", name:"Salami blokjes", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:9.79, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/08/36/asset-2120836.jpg"},
        {id:19, brand:"BONI", name:"Salami Milano GV", category:["Vlees"], subcategory:["Charcuterie", "Salami"], amount:1, price:3.31, description:"Een huisgemaakte salami van rundsvlees, bereid volgens het authentieke recept van Vincent senior. Deze droge salami is verkrijgbaar met of zonder look en kies je dus best afhankelijk van met wie je de dag zelf nog zult afspreken.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/57/96/asset-1525796.jpg"},

        {id:20, brand:"HERTA", name:"Superieur ham natuur 3 sn.", category:["Vlees"], subcategory:["Charcuterie", "Ham"], amount:1, price:2.25, description:"Gekookte hesp/ham op ambachtelijke wijze gemaakt volgens het recept van Kai Meyers. Voor mij 'ene me hesp' alsjeblieft!", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/53/93/asset-2095393.jpg"},
        {id:21, brand:"AH", name:"Mosterdspek", category:["Vlees"], subcategory:["Charcuterie", "Ham"], amount:1, price:2.16, description:"Gekookte hesp/ham op ambachtelijke wijze gemaakt volgens het recept van Kai Meyers. Voor mij 'ene me hesp' alsjeblieft!", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/80/03/asset-2708003.jpg"},
        {id:22, brand:"BONI BIO", name:"Gekookte ham", category:["Vlees"], subcategory:["Charcuterie", "Ham"], amount:1, price:4.55, description:"Gekookte hesp/ham op ambachtelijke wijze gemaakt volgens het recept van Kai Meyers. Voor mij 'ene me hesp' alsjeblieft!", nutriScore:"c", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/08/55/asset-2130855.jpg"},
        {id:23, brand:"EVERYDAY", name:"Ham ovengebakken", category:["Vlees"], subcategory:["Charcuterie", "Ham"], amount:1, price:3.98, description:"Gekookte hesp/ham op ambachtelijke wijze gemaakt volgens het recept van Kai Meyers. Voor mij 'ene me hesp' alsjeblieft!", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/24/54/asset-912454.jpg"},

        {id:24, brand:"AH", name:"Beenhamsalade", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:1.85, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/30/13/asset-2503013.jpg"},
        {id:25, brand:"DÉLIO", name:"Salade kip curry", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:3.39, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/37/89/asset-1523789.jpg"},
        {id:26, brand:"BONI", name:"Gv vleessalade", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:1.84, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/82/74/asset-2428274.jpg"},
        {id:27, brand:"EVERYDAY", name:"Tonijnsalade", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:1.09, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/83/10/asset-2428310.jpg"},
        {id:28, brand:"BONI", name:"Orientaalse salade", category:["Vlees"], subcategory:["Charcuterie", "Salade"], amount:1, price:1.80, description:"Overheerlijke salade vers gemaakt door onze beenhouder met liefde. Deze salade is gemaakt op basis van mayonaise.", nutriScore:"d", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/74/29/asset-2617429.jpg"},

        {id:29, brand:"AOSTE", name:"Crèmepaté", category:["Vlees"], subcategory:["Charcuterie", "Paté"], amount:1, price:2.13, description:"Een smeuïge crèmepaté die werd afgewerkt met stukjes appel om bij elke hap een lichtzoete toets vrij te geven. Ideaal voor op de boterham, maar zeker ook een aanrader voor op toastjes bij een aperitiefje.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/04/76/asset-850476.jpg"},
        {id:30, brand:"BONI", name:"Boerenpaté", category:["Vlees"], subcategory:["Charcuterie", "Paté"], amount:1, price:2.06, description:"Een smeuïge crèmepaté die werd afgewerkt met stukjes appel om bij elke hap een lichtzoete toets vrij te geven. Ideaal voor op de boterham, maar zeker ook een aanrader voor op toastjes bij een aperitiefje.", nutriScore:"e", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/42/39/asset-594239.jpg"},
        {id:31, brand:"EVERYDAY", name:"Crèmepaté vlootje", category:["Vlees"], subcategory:["Charcuterie", "Paté"], amount:1, price:0.89, description:"Een smeuïge crèmepaté die werd afgewerkt met stukjes appel om bij elke hap een lichtzoete toets vrij te geven. Ideaal voor op de boterham, maar zeker ook een aanrader voor op toastjes bij een aperitiefje.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/37/06/asset-2053706.jpg"},

        {id:32, brand:"HERTA", name:"Kip aan spit -25% zout", category:["Vlees"], subcategory:["Charcuterie", "Kip & kalkoen"], amount:1, price:2.99, description:"Kippenwit is te danken aan het exclusieve gebruik van de magerste en zuiverste kipfilets (100% filet). De filets worden op dezelfde wijze bereid als gekookte ham. Daarna geeft het ambachtelijke bakproces in de oven de filets een lekkere grillsmaak evenals het mooie, goudbruine korstje.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/66/41/asset-2446641.jpg"},
        {id:33, brand:"AOSTE", name:"Disney kipworstj familypack", category:["Vlees"], subcategory:["Charcuterie", "Kip & kalkoen"], amount:1, price:4.49, description:"Kippenwit is te danken aan het exclusieve gebruik van de magerste en zuiverste kipfilets (100% filet). De filets worden op dezelfde wijze bereid als gekookte ham. Daarna geeft het ambachtelijke bakproces in de oven de filets een lekkere grillsmaak evenals het mooie, goudbruine korstje.", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/00/37/asset-2790037.jpg"},
        {id:34, brand:"AOSTE PLUS", name:"Kip.stukj.gegrild natuur", category:["Vlees"], subcategory:["Charcuterie", "Kip & kalkoen"], amount:1, price:2.49, description:"Kippenwit is te danken aan het exclusieve gebruik van de magerste en zuiverste kipfilets (100% filet). De filets worden op dezelfde wijze bereid als gekookte ham. Daarna geeft het ambachtelijke bakproces in de oven de filets een lekkere grillsmaak evenals het mooie, goudbruine korstje.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/83/43/asset-2788343.jpg"},
        {id:35, brand:"BONI", name:"Mini gevogelte balletjes", category:["Vlees"], subcategory:["Charcuterie", "Kip & kalkoen"], amount:1, price:3.99, description:"Kippenwit is te danken aan het exclusieve gebruik van de magerste en zuiverste kipfilets (100% filet). De filets worden op dezelfde wijze bereid als gekookte ham. Daarna geeft het ambachtelijke bakproces in de oven de filets een lekkere grillsmaak evenals het mooie, goudbruine korstje.", nutriScore:"b", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/22/76/asset-2132276.jpg"},
        ////////////////////////////////////////////////////////////////GROENTEN////////////////////////////////////////////////////////////////
        {id:36, brand:"FLORETTE", name:"Kropsla fijne kruiden", category:["Groenten"], subcategory:["Sla"], amount:1, price:2.89, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/93/99/asset-2439399.jpg"},
        {id:37, brand:"BONI BIO", name:"Jonge sla", category:["Groenten"], subcategory:["Sla"], amount:1, price:1.99, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/90/32/asset-2419032.jpg"},
        {id:38, brand:"FLANDRIA", name:"Sla multicolor", category:["Groenten"], subcategory:["Sla"], amount:1, price:1.15, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/28/14/asset-392814.jpg"},
        {id:39, brand:"AH", name:"Ijsbergsla", category:["Groenten"], subcategory:["Sla"], amount:1, price:0.99, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/46/74/asset-1224674.jpg"},
        {id:40, brand:"BONI", name:"Rauwkostmix", category:["Groenten"], subcategory:["Wortel","Witte kool"], amount:1, price:1.19, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/55/46/asset-2475546.jpg"},
        {id:41, brand:"BONI", name:"Geraspte wortelen", category:["Groenten"], subcategory:["Wortel"], amount:1, price:0.55, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/55/45/asset-2475545.jpg"},
        {id:42, brand:"BONI", name:"Witte kool geraspt", category:["Groenten"], subcategory:["Witte kool"], amount:1, price:1.19, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/58/50/asset-2675850.jpg"},
        {id:43, brand:"SALANOVA", name:"Sla mix", category:["Groenten"], subcategory:["Sla"], amount:1, price:0.99, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/62/91/asset-2136291.jpg"},
        {id:44, brand:"BONI", name:"Mix kiemen", category:["Groenten"], subcategory:["Kiemen"], amount:1, price:1.89, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/18/58/asset-2451858.jpg"},
        {id:45, brand:"AH", name:"Andijvie", category:["Groenten"], subcategory:["Andijvie"], amount:1, price:1.89, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/20/95/asset-362095.jpg"},
        {id:46, brand:"TOMA'", name:"Box tomaten", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:4.99, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/42/07/asset-1744207.jpg"},
        {id:47, brand:"AH", name:"Tomaten extra", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:2.39, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/71/29/asset-1147129.jpg"},
        {id:46, brand:"BONI", name:"Kerstomaatjes tros", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:2.99, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/00/29/asset-2330029.jpg"},
        {id:49, brand:"AGROMONTE", name:"Pass.salsa kerstom. glas", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:2.89, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/45/46/asset-2274546.jpg"},
        {id:50, brand:"ELVEA", name:"Tomaten blokjes gepeld", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:1.99, description:"", nutriScore:"n/a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/89/30/asset-1718930.jpg"},
        {id:51, brand:"BONI", name:"Taboulé paprika-tomaat", category:["Groenten"], subcategory:["Tomaten"], amount:1, price:2.29, description:"", nutriScore:"a", previewImg:"https://images.collectandgo.be/images/step/JPG/JPG/500x500/std.lang.all/76/14/asset-2797614.jpg"},
        

  ];



//export default{
//  dataObject
//}